<h1 align=center><font size = 7>NumPy</font></h1>



## Table of Exercises!

01. [Question 01](#question01)
2. [Question 02](#question02).
3. [Question 03](#question03).
4. [Question 04](#question04).
5. [Question 05](#question05).
6. [Question 06](#question06).
7. [Question 07](#question07).
8. [Question 08](#question08).
9. [Question 09](#question09).



<a id='item312'></a>


<a id='question01'></a>
## Question 01




In [2]:
import numpy as np
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

<a id='question02'></a>
## Question 02




In [5]:
import numpy as np
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<a id='question03'></a>
## Question 03




In [11]:
import numpy as np
np.arange(20,61)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

<a id='question04'></a>
## Question 04




In [13]:
import numpy as np
np.arange(15,56,2)

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47,
       49, 51, 53, 55])

<a id='question05'></a>
## Question 05




In [30]:
import numpy as np 
np.random.uniform(size=15)

array([0.5100772 , 0.31414859, 0.53277953, 0.0721009 , 0.07373317,
       0.69852358, 0.86366438, 0.73147467, 0.97173444, 0.61243191,
       0.43398298, 0.2531718 , 0.64430776, 0.57127473, 0.07028242])

<a id='question06'></a>
## Question 06




In [25]:
import numpy as np
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<a id='question07'></a>
## Question 07




In [29]:
import numpy as np
np.random.randn(3,5)

array([[-0.05005824,  0.7981076 , -1.1171311 ,  1.40337913, -1.44709055],
       [-0.3887076 , -1.00474557, -2.12363758, -0.01291527, -0.12486597],
       [-0.98713083,  0.75092605,  1.6915183 , -0.09293287,  0.01067048]])

<a id='question08'></a>
## Question 08




In [19]:
import numpy as np
np.linspace(0,1,13)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

<a id='question09'></a>
## Question 09




In [24]:
import numpy as np
np.random.normal(loc=6,scale=4,size=(4,6))

array([[ 6.24217807,  1.71392105,  5.84649317,  8.27590829,  2.46747569,
         6.4694524 ],
       [ 5.94555318, -2.53953152,  4.11161427,  6.81413305,  8.72295675,
         5.0883607 ],
       [ 4.05849528,  4.62609808,  3.96051061, -0.06773406, 15.72589849,
        12.59106725],
       [ 9.10157044,  8.14819074, 16.07204022, 14.15295848, -0.47358622,
         0.85907183]])

## Best Wishes!


